app:
  feign-api-keys:
    exchange: ${EXCHANGE_API_KEY}
  schedule:
    exchange: ${UPDATE_PERIOD}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  cloud:
    openfeign:
      client:
        config:
          exchange:
            url: http://api.exchangeratesapi.io/v1/
